MODULE particle_swarm
FUNCTION PS_GETPROPERTY 1 1
FUNCTION PS_DONE 0 0
FUNCTION PS_OPTIMIZE 0 0 KEYWORDS
PROCEDURE PS_CONFIGURE 2 2
PROCEDURE PS_SETPROPERTY 2 2
PROCEDURE PS_INITIALIZE 0 0
PROCEDURE PS_STEP 0 0
